### ISSUE TITLE
Crashes with IsADirectoryError on latest master

### ISSUE THREAD

**Issue by TheTechRobo** [akx/cachemoney#4]
```
~/cachemoney git:master ❯❯❯ python3 -m cachemoney --cache-dir ../.cache/chromium/Default/Cache/ --output-root files --filter "*tracker.archiveteam*"
_dk_http://archiveteam.org http://archiveteam.org http://tracker.archiveteam.org:8080/socket.io/1/?t=1648672115003
Traceback (most recent call last):
  File "/opt/python-3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/python-3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/thetechrobo/cachemoney/cachemoney/__main__.py", line 49, in <module>
    main()
  File "/home/thetechrobo/cachemoney/cachemoney/__main__.py", line 41, in main
    with open(output_path, "wb") as outf:
IsADirectoryError: [Errno 21] Is a directory: 'files/_dk_http://archiveteam.org http://archiveteam.org http://tracker.archiveteam.org:8080/socket.io/1/'
```
Also happens with other ones. I am **not** using the --decompress flag (I want to see if it works)

**Comment by akx** [comment]
Ah, that would probably happen with a bunch of cache paths with one creating a directory and another that wouldn't (ie. x/1 and x)...
